### ISSUE TITLE
Traceback: IndexError: list index out of range

### ISSUE THREAD

**Issue by LYS1THEA** [royvds/assGrammarCheck#1]
```
C:\Users\USERNAME\Downloads\assGrammarCheck>assgrammarcheck -l en-US -i "01.ENG.ass"
Setting up GrammarChecker and LanguageTool server...
Done!
Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\Scripts\assGrammarCheck.exe\__main__.py", line 7, in <module>
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\assgrammarcheck\cli.py", line 78, in main
    check(args.input, grammar_checker)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\assgrammarcheck\cli.py", line 26, in check
    mistakes = checker.get_subtitle_mistakes(subtitle)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\assgrammarcheck\assgrammarcheck.py", line 144, in get_subtitle_mistakes
    prev_event = subtitle.events[index+index_offset]
  File "C:\Users\USERNAME\AppData\Roaming\Python\Python39\site-packages\ass\section.py", line 52, in __getitem__
    return self._lines[index]
IndexError: list index out of range
```

**Comment by rosvob** [comment]
Can you share the .ass file?

**Comment by LYS1THEA** [comment]
[yep](https://files.catbox.moe/ifi5w9.ass)
